"""empty message

Revision ID: f24babcd3e08
Revises: 
Create Date: 2025-02-10 14:53:59.783914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24babcd3e08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('energy', sa.BigInteger(), nullable=True),
    sa.Column('bandwidth', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_info_address'), 'query_info', ['address'], unique=False)
    op.create_index(op.f('ix_query_info_id'), 'query_info', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_info_id'), table_name='query_info')
    op.drop_index(op.f('ix_query_info_address'), table_name='query_info')
    op.drop_table('query_info')
    # ### end Alembic commands ###
